import os

from typing import Annotated, Any, Optional, Union

from fastapi import FastAPI, Body, HTTPException
from dotenv import load_dotenv
from pydantic import BaseModel
from numpydantic import NDArray, Shape

from core.utils import check_folder_exists
from core.simpleml import ModelAdapter
from core.enums import TargetType


load_dotenv()

if "CODE_DIR" not in os.environ:
  raise RuntimeError("CODE_DIR not defined in environment variables.")

app = FastAPI()


class Input(BaseModel):
    """
    json schema of the input data to be scored by the /predict endpoint.

    Schema
    ------
    index: the list of indexes
    columns: the list of column (feature) names
    data: the list of data to be scored
    """
    index: list
    columns: list
    data: list


class PredictResponse(BaseModel):
    """
    Raw response for predictions generated by custom models.

    Schema
    ------
    predictions: predictions returned by the model.
    columns: list of columns.
    """
    predictions: NDArray[Shape["*, 1"], int]
    columns: Optional[NDArray[Shape["1"], Any]] = None


@app.get("/")
def main():
    return {"Hello": "World"}


@app.post("/predict", response_model=PredictResponse)
def predict(
    input: Annotated[Input, Body(embed=True)],
    target_type: Annotated[TargetType, Body(embed=True)] = None
):
    code_dir = os.environ['CODE_DIR']

    if not check_folder_exists(code_dir):
        raise HTTPException(status_code=404, detail=f"The following code_dir {code_dir} cannot be found")

    m_adapter = ModelAdapter(code_dir, target_type or TargetType.BINARY)
    m_adapter.load_custom_hooks()
    model = m_adapter.load_model_from_artifact()
    preds = m_adapter.predict(model, binary_data=input, mimetype="")

    return PredictResponse(predictions=preds.values, columns=preds.columns.values)


@app.post("/batch-predict")
def batch_predict():
    batch_preds = {}
    return batch_preds


@app.post("/transform")
def transform():
    batch_preds = {}
    return batch_preds
