from typing import Any, Dict

import pandas as pd


def transform(data: pd.DataFrame, model: Any = None) -> pd.DataFrame:
    """
    This hook may not have to be implemented by your model.
    
    Modify this method to add data transformation before the data is scored.
    For example, this method can be used to implement one-hot encoding for models
    that don't include it on their own.

    Params
    ______
    data: pd.DataFrame
    model: object, deserialized model

    Returns
    -------
    pd.DataFrame
    """
    # Add transformation steps needed before passing the data for scoring
    # i.e: Remove target columns
    target_col = "Species"
    id_col = "Id"

    if target_col in data.columns:
        data = data.drop(target_col, axis=1)

    if id_col in data.columns:
        data = data.drop(id_col, axis=1)

    return data


# NOTE: In this template, "sklearn_reg.pkl" is automatically loaded from CODE_DIR
#
# Some hooks are omitted as they are implicitly generated by the library.
# If needed, they can be overriden in order to change their default behavior:
# Look in README.md to see supported types of models.
#
# def load_model(code_dir: str) -> Any:
#     ...
#
# def score(data, model, **kwargs):
#     ...
